### ISSUE TITLE
Any Ideas on how to incorporate serverless express component ?

### ISSUE THREAD

**Issue by Suedo** [International-Slackline-Association/Rankings-Backend#5]
First of all, a big thank you for making this open source. This is the best resource I have found for using serverless framework with NestJs. Learning a lot from here!

I wanted to ask, given the GA release of [Serverless express component](https://github.com/serverless-components/express), which greatly [improves](https://www.serverless.com/blog/serverless-components-ga/) deployment speed, If you would have any ideas to share on how to incorporate the same into a NestJS + Serverless application.

**Comment by Can-Sahin** [comment]
Your welcome. I made it open source to set as an example. Not everything here is right by the way. It gets old in time. Make sure you check the latest updates and recommended usages


For the question...No idea. I am not fan of serverless components for now. They arent fully mature and they dont use cloudformation templates (last time I checked)
